rootProject.name = 'GameVerse'

include ':core'
include ':player'
include ':games:core'
include ':games:chess'
include ':games:snake'
include ':games:pong'
include ':games:tictactoe'
include ':games:memory'
include ':games:racing'
include ':achievements'
include ':rewards'
include ':leaderboard'
include ':database'
include ':ui'
